version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map container's port 80 to host's port 8080
    networks:
      - it210-network

# networks:
#   it210-network:
#     external: true
